package dev.ilamparithi.aournalpp.runtime

import android.content.Context
import android.net.Uri
import android.util.Log
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File

class PdfExportManager(
    private val env: LinuxEnvironment,
    private val supervisor: ProcessSupervisor
) {
    companion object {
        private const val TAG = "PdfExportManager"
    }

    suspend fun convertXoppToPdf(xoppFile: File, outputPdfFile: File): Result<File> =
        withContext(Dispatchers.IO) {
            runCatching {
                if (!xoppFile.exists() || xoppFile.length() == 0L) {
                    error("Source note file does not exist or is empty: ${xoppFile.absolutePath}")
                }

                outputPdfFile.parentFile?.mkdirs()
                if (outputPdfFile.exists()) {
                    outputPdfFile.delete()
                }

                val xoppBinary = env.resolveExecutable("xournalpp")
                if (!xoppBinary.exists() || !xoppBinary.canExecute()) {
                    error("Xournal++ binary not found or not executable at: ${xoppBinary.absolutePath}")
                }

                Log.i(TAG, "Starting headless PDF conversion: ${xoppFile.name} -> ${outputPdfFile.name}")
                val (exitCode, output) = supervisor.runBinary(
                    listOf(
                        xoppBinary.absolutePath,
                        "-p",
                        outputPdfFile.absolutePath,
                        xoppFile.absolutePath
                    )
                )

                if (exitCode != 0) {
                    Log.e(TAG, "PDF conversion failed with exit code $exitCode. CLI output: $output")
                    error("Xournal++ PDF export failed with exit code $exitCode: $output")
                }

                if (!outputPdfFile.exists() || outputPdfFile.length() == 0L) {
                    Log.e(TAG, "PDF file was not created or has 0 bytes: ${outputPdfFile.absolutePath}")
                    error("PDF file was not generated by Xournal++.")
                }

                Log.i(TAG, "Successfully generated PDF (${outputPdfFile.length()} bytes) at ${outputPdfFile.absolutePath}")
                outputPdfFile
            }
        }

    suspend fun exportPdfToUri(context: Context, xoppFile: File, destUri: Uri): Result<Unit> =
        withContext(Dispatchers.IO) {
            runCatching {
                val tempPdf = File(env.tmpDir, "export_${System.currentTimeMillis()}_${xoppFile.nameWithoutExtension}.pdf")
                try {
                    convertXoppToPdf(xoppFile, tempPdf).getOrThrow()

                    context.contentResolver.openOutputStream(destUri)?.use { outStream ->
                        tempPdf.inputStream().use { inStream ->
                            inStream.copyTo(outStream)
                        }
                    } ?: error("Failed to open destination URI for writing")

                    Log.i(TAG, "Successfully streamed PDF export to $destUri")
                    Unit
                } finally {
                    if (tempPdf.exists()) {
                        tempPdf.delete()
                    }
                }
            }
        }

    suspend fun renderPdfForSharing(context: Context, xoppFile: File): Result<File> =
        withContext(Dispatchers.IO) {
            runCatching {
                val sharedDir = File(context.cacheDir, "shared_pdfs").apply { mkdirs() }
                val cleanName = "${xoppFile.nameWithoutExtension}.pdf"
                val destPdf = File(sharedDir, cleanName)

                convertXoppToPdf(xoppFile, destPdf).getOrThrow()
                destPdf
            }
        }
}
